### ISSUE TITLE
wont compile

### ISSUE THREAD

**Issue by EXC3L-YT** [wtfchloe/sapphire#4]
im compiling as release x64 and i get 3 errors
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'return': cannot convert from 'bool' to 'c_chai_base_player'	87

**Comment by Devourgod** [comment]
I have the same problem

**Comment by Tyler-Admin** [comment]
return true

**Comment by wtfchloe** [comment]
replace the return false with return c_chai_base_player(0);
